# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: sudo apt install npm -y
    - run: npm run build --if-present
    - run: pwd
    - run: ls
    - run: npm test
  provisionProd:
    name: Provision Prod
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: .prod
      url: https://abel-node-gh-accelerator.azurewebsites.net
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
  deploy:
    name: Push to EC2 Instance
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
         SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
         REMOTE_HOST: ${ { secrets.HOST_DNS }}
         REMOTE_USER: ${ { secrets.USERNAME }}
         TARGET: ${ { secrets.TARGET_DIR }}
